# Perpusatakan_Juwantoro 
# Daftar Buku yang ada di Perpustakaan Juwantoro, User Silahkan Masukkan daftar buku

List_Daftar_Buku = [
    {
        "ID_Buku"       : "001",
        "Judul_Buku"    : "Hitler's Secrets",
        "Penulis"       : "Adam Lebor",
        "Penerbit"      : "Citadel Press",
        "Genre"         : "Historical",
        "stok_buku"     : 5,
    }
    ,{
        "ID_Buku"       : "002",
        "Judul_Buku"    : "The Middle Stories",
        "Penulis"       : "Sheila Heti",
        "Penerbit"      : "House of Anansi Press",
        "Genre"         : "Fiction",
        "stok_buku"     : 2,
    }
    ,{
        "ID_Buku"       : "003",
        "Judul_Buku"    : "Our Dumb",
        "Penulis"       : "The Onion",
        "Penerbit"      : "Three Rivers Press",
        "Genre"         : "Humoresque",
        "stok_buku"     : 3,
    }
    ,{
        "ID_Buku"       : "004",
        "Judul_Buku"    : "Tell Me Now",
        "Penulis"       : "Robynn Clairday",
        "Penerbit"      : "Scholastic",
        "Genre"         : "Fantasy",
        "stok_buku"     : 7,
    }
    ,{
        "ID_Buku"       : "005",
        "Judul_Buku"    : "Pigs in Heaven",
        "Penulis"       : "Barbara Kingsolver",
        "Penerbit"      : "Harpercollins",
        "Genre"         : "Non-Fiction",
        "stok_buku"     : 4,
    }
]
